language: cpp

os: linux  # Сборка на Linux

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake

script:
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
